"""Initial Phase 3 schema with UUID

Revision ID: 66ecd805a88d
Revises: 
Create Date: 2025-12-31 23:06:47.527849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ecd805a88d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # Create new integer ID column
    op.add_column('tasks', sa.Column('new_id', sa.Integer(), nullable=True))

    # Populate new_id with sequential integers
    op.execute("""
        UPDATE tasks
        SET new_id = subquery.row_num
        FROM (
            SELECT id as old_id, ROW_NUMBER() OVER (ORDER BY created_at) as row_num
            FROM tasks
        ) subquery
        WHERE tasks.id = subquery.old_id
    """)

    # Drop old id column and constraints
    op.drop_constraint('tasks_pkey', 'tasks', type_='primary')
    op.drop_column('tasks', 'id')

    # Rename new_id to id
    op.alter_column('tasks', 'new_id', new_column_name='id', nullable=False)

    # Create new primary key
    op.create_primary_key('tasks_pkey', 'tasks', ['id'])

    # Add auto-increment sequence
    op.execute("""
        CREATE SEQUENCE tasks_id_seq;
        SELECT setval('tasks_id_seq', (SELECT MAX(id) FROM tasks));
        ALTER TABLE tasks ALTER COLUMN id SET DEFAULT nextval('tasks_id_seq');
    """)

    # Add status and priority with defaults for existing rows
    op.add_column('tasks', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Set defaults based on completed column
    op.execute("""
        UPDATE tasks
        SET status = CASE WHEN completed THEN 'completed' ELSE 'pending' END,
            priority = 'medium'
    """)

    # Make columns non-nullable
    op.alter_column('tasks', 'status', nullable=False)
    op.alter_column('tasks', 'priority', nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tasks_completed'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_completed'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'completed')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # Add completed column back based on status
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), nullable=True))
    op.execute("""
        UPDATE tasks
        SET completed = (status = 'completed')
    """)
    op.alter_column('tasks', 'completed', nullable=False, server_default=sa.text('false'))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_user_completed'), 'tasks', ['user_id', 'completed'], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('idx_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('idx_tasks_completed'), 'tasks', ['completed'], unique=False)
    op.alter_column('tasks', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'status')

    # Drop the sequence and convert ID back to UUID
    op.execute("DROP SEQUENCE IF EXISTS tasks_id_seq CASCADE")

    # Create new UUID column
    op.add_column('tasks', sa.Column('new_id', sa.UUID(), nullable=True))

    # Generate UUIDs for existing rows
    op.execute("""
        UPDATE tasks
        SET new_id = gen_random_uuid()
    """)

    # Drop old integer id column
    op.drop_constraint('tasks_pkey', 'tasks', type_='primary')
    op.drop_column('tasks', 'id')

    # Rename new_id to id
    op.alter_column('tasks', 'new_id', new_column_name='id', nullable=False)

    # Create primary key
    op.create_primary_key('tasks_pkey', 'tasks', ['id'])
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
